[build]
command = "cd frontend && rm -f package-lock.json && npm install && npm run build"
pages_build_output_dir = "frontend/.next"

[env.production]
NODE_VERSION = "20"
NPM_VERSION = "10"
NEXT_TELEMETRY_DISABLED = "1"
CLOUDFLARE_FORCE_CLEAN_BUILD = "true"

[env.preview]
NODE_VERSION = "20"
NPM_VERSION = "10"
NEXT_TELEMETRY_DISABLED = "1"
CLOUDFLARE_FORCE_CLEAN_BUILD = "true"

# Enable improved Node.js compatibility
[compatibility_flags]
nodejs_compat = true 