[build]
command = "npm install && cd frontend && npm install && npm run build"
output_directory = "frontend/.next"

[env.production]
NODE_VERSION = "20"
NPM_VERSION = "10"
NEXT_TELEMETRY_DISABLED = "1"

[env.preview]
NODE_VERSION = "20"
NPM_VERSION = "10"
NEXT_TELEMETRY_DISABLED = "1"

# Enable improved Node.js compatibility
[compatibility_flags]
nodejs_compat = true 